# Config file for automatic testing at travis-ci.org

language: python
python: 3.7
dist: xenial
sudo: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
    - pip install -r test_requirements.txt
    - nosetests -v --with-xcoverage --cover-package=vial

after_success:
    - coveralls
